[package]
name = "acrux-core"
description = "Types de base, erreurs, journalisation, accès fichier"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]

[lints]
workspace = true
