[package]
name = "acrux-winres"
description = "Écriture des ressources Windows (.res) : icône et informations de version des exécutables"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]

[lints]
workspace = true
